context:
  name: "libtommath"
  version: "1.3.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://github.com/libtom/${{ name }}/releases/download/v${{ version }}/ltm-${{ version }}.tar.xz
  sha256: 296272d93435991308eb73607600c034b558807a07e829e751142e65ccfa9d08

build:
  number: 1
  script:
    - if: win
      then: |
        cmake -GNinja ^
            -D BUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% -DBUILD_SHARED_LIBS=On ^
            %SRC_DIR%
        ninja install
      else: |
        cmake -GNinja \
              -DBUILD_TESTS=OFF -DCMAKE_INSTALL_PREFIX=$PREFIX -DBUILD_SHARED_LIBS=On \
              $SRC_DIR
        ninja install

requirements:
  build:
    - ${{ compiler("c") }}
    - cmake
    - ninja
  run_exports:
    strong:
      - ${{ pin_subpackage("libtommath", upper_bound="x.x.x") }}

tests:
  - package_contents:
      strict: true
      lib:
        - tommath
      include:
        - tommath.h
      files:
        - lib/cmake/libtommath/libtommath-*.cmake
        - lib/pkgconfig/libtommath.pc

about:
  homepage: https://www.libtom.net/LibTomMath/
  license: Unlicense
  license_file: LICENSE
  summary: LibTomMath is a free open source portable number theoretic multiple-precision integer library written entirely in C. 
  description: |
    LibTomMath is a free open source portable number theoretic multiple-precision integer library written entirely in C. (phew!). The library is designed to provide a simple to work with API that provides fairly efficient routines that build out of the box without configuration.

    The library builds out of the box with GCC 2.95 [and up] as well as Visual C++ v6.00 [with SP5] without configuration. The source code is arranged to make it easy to dive into a particular area very quickly. The code is also littered with comments [This is one of the on going goals] that help explain the algorithms and their implementations. Ideally the code will serve as an educational tool in the future for CS students studying number theory.
  repository: https://github.com/libtom/libtommath
  documentation: https://github.com/libtom/libtommath/releases/download/v1.3.0/bn-1.3.0.pdf
