context:
  name: "MoarVM"
  version: "2025.06"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/${{ name }}/${{ name }}/releases/download/${{ version }}/${{ name }}-${{ version }}.tar.gz
  sha256: e8d6b00cdb3f99022ade2a843a7a8ec87f66a38bb5655f85d50351c6b3b8d257

build:
  script: |
    perl Configure.pl --c11-atomics --has-libffi --has-libtommath --has-mimalloc --has-libuv --optimize --prefix=$PREFIX # --pkgconfig=$PKG_CONFIG_PATH
    make realclean
    make -j$CPU_COUNT
    make install

requirements:
  build:
    - ${{ compiler("c") }}
    - pkgconf
  host:
    - libtommath
    - mimalloc
    - zstd
    - libuv
    - libffi
  run:
    - libtommath
    - mimalloc
    - zstd
    - libuv
    - libffi

tests:
  - script:
    - moar --version
    - moar --help
