name: Build all packages

# this is important for trusted publishing
permissions:
  id-token: write

on:
  push:
    branches:
      - main
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        include:
          - { target: linux-64, os: ubuntu-latest }
          - { target: win-64, os: windows-latest }
          - { target: osx-arm64, os: macos-latest }
      fail-fast: false

    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.52.0

      - name: Add .pixi/envs/default/bin to the $PATH
        shell: bash
        run: |
          echo "$(pwd)/.pixi/envs/default/bin" >> $GITHUB_PATH

      - name: Run code in changed subdirectories
        shell: bash
        run: |
          rattler-build build --recipe-dir . \
            --skip-existing=all --target-platform=${{ matrix.target }} \
            -c conda-forge -c https://prefix.dev/remis-forge

      - name: Upload all packages
        shell: bash
        # do not upload on PR
        if: github.event_name == 'push'
        run: |
          # uses trusted publishers for the upload
          for file in output/**/*.conda; do
            rattler-build upload prefix -c remis-forge "$file"
          done
